global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#main'
