version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
        
  ui:
    image: ${US}/ui:${VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net

  post:
    image: ${US}/post:${VERSION}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post

  comment:
    image: ${US}/comment:${VERSION}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
volumes:
  post_db:


networks:
  front_net:
  back_net:

