version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
        
  ui:
    image: ${US}/ui:${VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net

  post:
    image: ${US}/post:${VERSION}
    networks:
      - back_net
      - front_net

  comment:
    image: ${US}/comment:${VERSION}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${US}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

volumes:
  prometheus_data:
  post_db:


networks:
  front_net:
  back_net:
