kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: HDjv64Boi+PLr/CCW+FH+fCV44IBMWD9Ek1zre3tCUs=
      - identity: {}
