version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
        
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
    volumes:
      - /home/docker-user/ui:/app

  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION}
    networks:
      - back_net
      - front_net
    volumes:
      - /home/docker-user/post:/app

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION}
    networks:
      - back_net
      - front_net
    volumes:
      - /home/docker-user/comment:/app

volumes:
  post_db:

networks:
  front_net:
  back_net:
